export enum VehicleType {
    SEDAN = 'SEDAN',
    HATCHBACK = 'HATCHBACK',
    SUV = 'SUV',
    BAKKIE = 'BAKKIE',
    TRUCK = 'TRUCK',
    MOTORBIKE = 'MOTORBIKE',
    TAXI = 'TAXI',
    VAN = 'VAN',
    OTHER = 'OTHER'
}

export enum VehicleCondition {
    GOOD = 'GOOD',
    DAMAGED = 'DAMAGED',
    OKAY = 'OKAY',
    BAD = 'BAD'
}

export enum VehicleStatus {
  STOLEN = 'STOLEN',
  WANTED = 'WANTED',
  INVOLVED_IN_CRIME = 'INVOLVED_IN_CRIME',
  FOUND = 'FOUND',
  ACTIVE = 'ACTIVE',
  MISSING = 'MISSING',
  ABANDONED = 'ABANDONED',
  ACCIDENT_INVOLVED = 'ACCIDENT_INVOLVED',
  IMPOUNDED = 'IMPOUNDED',
  SEIZED = 'SEIZED',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  IN_REPAIR = 'IN_REPAIR',
  WRITTEN_OFF = 'WRITTEN_OFF',
  DECOMMISSIONED = 'DECOMMISSIONED',
  UNKNOWN = 'UNKNOWN',
}